### ISSUE TITLE
Not able to view report in klov when the report contains 3000+ test

### ISSUE THREAD

**Issue by puneetkapoor18** [extent-framework/klov#55]
Hi,

I am running my regression suite and it consists of 3000+ test cases when I open the klov dashboard to view the result it doesn't load the report. Although when I run my smoke or sanity jobs (~300 test case) it is showing perfectly fine.

Could you please let me know that is there any limitation in klov as I am not able to see the results when the test cases are more than 3000+

Note : Extent report version 3.1.5 and klov version 0.1.1

Regards

**Comment by puneetkapoor18** [comment]
The loading time for the report is too high if we have lot of data in db. Could you please let me know how to fix this @anshooarora

**Comment by juancarames** [comment]
Hi, i have the same problem. 
klov return the api information correctly, but the problem is in mongo db query, if you wait a considerable time the report will showned. 
it will posible to improve mongo db perfomance? 
we are using klov 0.2.8 
my team (crowdar) bought a profesional version of extent recently.
Thanx.
